version: "3.7"
services:
    hadoop-namenode:
        hostname: hadoop-namenode
        restart: 'unless-stopped'
        image: local-hadoop:3.2.1
        environment: 
            - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
        ports:
            - "50070:50070"
            - "50075:50075"
            - "9000:9000"        
        command: /opt/hadoop/bin/hdfs namenode
        volumes:
            - "/home/pi/docker_host/hdfs/id_rsa:/root/.ssh/id_rsa"
            - "/home/pi/docker_host/hdfs/id_rsa.pub:/root/.ssh/id_rsa.pub"
            - "/home/pi/docker_host/hdfs/conf:/opt/hadoop/etc/hadoop"
            - "/home/pi/docker_host/persisted/hdfs/dfs:/data/dfs"
